# AgbCloud CLI Homebrew Tap æµ‹è¯•åŒ…åˆ†å‘æµæ°´çº¿
name: AgbCloud CLI Test Package Distribution

# è‡ªåŠ¨è§¦å‘æ¡ä»¶
triggers:
  push:
    branches:
      - master
      - main

# å…¨å±€å˜é‡
variables:
  BINARY_NAME: agbcloud
  OSS_BUCKET: agbcloud-internal
  OSS_ENDPOINT: oss-cn-hangzhou.aliyuncs.com
  BREW_TAP_REPO: git@gitlab.alibaba-inc.com:InnoArchClub/homebrew-agbcloud.git

# æµæ°´çº¿ä½œä¸šå®šä¹‰
jobs:
  # æž„å»ºã€æ‰“åŒ…ã€ä¸Šä¼ ã€éƒ¨ç½²
  build-and-deploy:
    name: æž„å»ºå¹¶éƒ¨ç½²
    runs-on: 4-16Gi
    timeout: 60m
    steps:
      - uses: checkout
      - uses: setup-env
        inputs:
          go-version: "1.23"
          go-mod-cache: true
          go-cache: false
      - id: build-binaries
        name: æž„å»ºå¤šå¹³å°äºŒè¿›åˆ¶æ–‡ä»¶
        run: |
          echo "Building for all platforms..."
          export VERSION="dev-$(date +%Y%m%d-%H%M)"
          export GIT_COMMIT=$(git rev-parse --short HEAD)
          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Building version: $VERSION"
          echo "Git commit: $GIT_COMMIT"
          make build-all
          ls -la bin/

      - id: create-packages
        name: åˆ›å»ºå®‰è£…åŒ…
        run: |
          echo "Creating packages..."
          export VERSION="dev-$(date +%Y%m%d-%H%M)"
          mkdir -p packages
          
          for binary in bin/*; do
            if [[ -f "$binary" ]]; then
              filename=$(basename "$binary")
              platform_arch=${filename#agbcloud-}
              
              temp_dir=$(mktemp -d)
              cp "$binary" "$temp_dir/agbcloud"
              tar -czf "packages/agbcloud-$VERSION-$platform_arch.tar.gz" -C "$temp_dir" agbcloud
              sha256sum "packages/agbcloud-$VERSION-$platform_arch.tar.gz" > "packages/agbcloud-$VERSION-$platform_arch.tar.gz.sha256"
              rm -rf "$temp_dir"
              echo "âœ“ Created package: agbcloud-$VERSION-$platform_arch.tar.gz"
            fi
          done
          
          ls -la packages/

      - id: upload-to-oss
        name: ä¸Šä¼ åˆ° OSS
        run: |
          echo "Uploading packages to OSS..."
          export VERSION="dev-$(date +%Y%m%d-%H%M)"
          
          # æ£€æŸ¥çŽ¯å¢ƒå˜é‡
          if [[ -z "$OSS_ACCESS_KEY_ID" ]] || [[ -z "$OSS_ACCESS_KEY_SECRET" ]]; then
            echo "Error: OSS credentials not set"
            exit 1
          fi
          
          # å®‰è£… ossutil
          if ! command -v ossutil >/dev/null 2>&1; then
            echo "Installing ossutil..."
            curl -L "https://gosspublic.alicdn.com/ossutil/1.7.19/ossutil-v1.7.19-linux-amd64.zip" -o ossutil.zip
            unzip -q ossutil.zip
            chmod +x ossutil*
            mv ossutil* /usr/local/bin/ossutil
            rm -f ossutil.zip
          fi
          
          # é…ç½®å¹¶ä¸Šä¼ 
          ossutil config -e "$OSS_ENDPOINT" -i "$OSS_ACCESS_KEY_ID" -k "$OSS_ACCESS_KEY_SECRET"
          
          for package in packages/*.tar.gz packages/*.sha256; do
            if [[ -f "$package" ]]; then
              filename=$(basename "$package")
              ossutil cp "$package" "oss://$OSS_BUCKET/agbcloud/releases/$filename" --force
              ossutil set-acl "oss://$OSS_BUCKET/agbcloud/releases/$filename" public-read
              echo "âœ“ Uploaded: $filename"
            fi
          done

      - id: update-homebrew-tap
        name: æ›´æ–° Homebrew Tap
        run: |
          echo "Updating Homebrew Tap..."
          export VERSION="dev-$(date +%Y%m%d-%H%M)"
          export GIT_COMMIT=$(git rev-parse --short HEAD)
          export TIMESTAMP=$(date +%Y%m%d-%H%M)
          export SANITIZED_TIMESTAMP=$(echo "$TIMESTAMP" | tr '-' '')
          
          # å…‹éš† tap ä»“åº“
          git clone "$BREW_TAP_REPO" homebrew-agbcloud
          cd homebrew-agbcloud
          
          # é…ç½® git
          git config user.name "Aone CICD Bot"
          git config user.email "cicd@alibaba-inc.com"
          
          # èŽ·å– SHA256 å€¼
          get_sha256() {
              local platform_arch=$1
              local sha256_file="../packages/agbcloud-$VERSION-$platform_arch.tar.gz.sha256"
              if [[ -f "$sha256_file" ]]; then
                  cut -d' ' -f1 "$sha256_file"
              else
                  echo "MISSING_SHA256"
              fi
          }
          
          DARWIN_AMD64_SHA256=$(get_sha256 "darwin-amd64")
          DARWIN_ARM64_SHA256=$(get_sha256 "darwin-arm64")
          LINUX_AMD64_SHA256=$(get_sha256 "linux-amd64")
          LINUX_ARM64_SHA256=$(get_sha256 "linux-arm64")
          
          # ç”Ÿæˆ Formula
          FORMULA_FILE="Formula/agbcloud@dev-$TIMESTAMP.rb"
          
          cat > "$FORMULA_FILE" << EOF
          class AgbcloudAT${SANITIZED_TIMESTAMP} < Formula
            desc "AgbCloud CLI - Test Build $TIMESTAMP"
            homepage "https://alibaba-inc.com/agbcloud"
            version "$VERSION"
          
            if OS.mac?
              if Hardware::CPU.arm?
                url "https://agbcloud-internal.oss-cn-hangzhou.aliyuncs.com/agbcloud/releases/agbcloud-$VERSION-darwin-arm64.tar.gz"
                sha256 "$DARWIN_ARM64_SHA256"
              else
                url "https://agbcloud-internal.oss-cn-hangzhou.aliyuncs.com/agbcloud/releases/agbcloud-$VERSION-darwin-amd64.tar.gz"
                sha256 "$DARWIN_AMD64_SHA256"
              end
            elsif OS.linux?
              if Hardware::CPU.arm?
                url "https://agbcloud-internal.oss-cn-hangzhou.aliyuncs.com/agbcloud/releases/agbcloud-$VERSION-linux-arm64.tar.gz"
                sha256 "$LINUX_ARM64_SHA256"
              else
                url "https://agbcloud-internal.oss-cn-hangzhou.aliyuncs.com/agbcloud/releases/agbcloud-$VERSION-linux-amd64.tar.gz"
                sha256 "$LINUX_AMD64_SHA256"
              end
            end
          
            def install
              bin.install "agbcloud"
            end
          
            test do
              system "#{bin}/agbcloud", "version"
            end
          
            def caveats
              <<~EOS
                This is a test build of AgbCloud CLI.
                Build timestamp: $TIMESTAMP
                Git commit: $GIT_COMMIT
                
                To switch between versions:
                  brew unlink agbcloud@${SANITIZED_TIMESTAMP}
                  brew link agbcloud@other-version
              EOS
            end
          end
          EOF
          
          # æäº¤æ›´æ”¹
          git add "$FORMULA_FILE"
          git commit -m "Add test build agbcloud@dev-$TIMESTAMP

          Version: $VERSION
          Git commit: $GIT_COMMIT
          Build timestamp: $TIMESTAMP"
          
          git push origin main
          
          echo "âœ… Homebrew Tap updated successfully!"
          echo "Users can install with: brew install agbcloud@dev-$TIMESTAMP"

      - id: send-notification
        name: å‘é€é€šçŸ¥
        run: |
          export VERSION="dev-$(date +%Y%m%d-%H%M)"
          export TIMESTAMP=$(date +%Y%m%d-%H%M)
          
          echo "ðŸŽ‰ AgbCloud CLI æµ‹è¯•åŒ…æž„å»ºå®Œæˆï¼
          
          ðŸ“¦ ç‰ˆæœ¬: $VERSION
          ðŸ•’ æ—¶é—´æˆ³: $TIMESTAMP
          ðŸ“ Git æäº¤: $(git rev-parse --short HEAD)
          
          ðŸº å®‰è£…å‘½ä»¤:
          brew install agbcloud@dev-$TIMESTAMP" 